- name: Config SSH
  local_action:
    module: file src="{{sshOrigDir}}" dest="{{homedir}}/.ssh" state=link

- name: Config AWS
  local_action:
    module: file src="{{awsOrigDir}}" dest="{{homedir}}/.aws" state=link
