- name: Create Git Local Path
  local_action:
    module: file path="{{ gitdir }}" state=directory mode=0755

- name: Clone dotfiles git repo
  local_action:
    module: git repo={{ git_remote_repo_dotfiles }} dest={{ git_local_repo_dotfiles }}

- name: Create Terminator Local Path
  local_action:
    module: file path="{{homedir}}/.config/terminator/" state=directory mode=0755

- name: Copy dotfiles
  local_action:
    module: file src="{{ git_local_repo_dotfiles }}/{{ item.src }}" dest="{{ item.dest }}" owner="{{user}}" group="{{user}}" state=hard force=yes
  with_items:
    - { src: 'bashrc', dest: '{{homedir}}/.bashrc' }
    - { src: 'curlrc', dest: '{{homedir}}/.curlrc' }
    - { src: 'gitconfig', dest: '{{homedir}}/.gitconfig' }
    - { src: 'vimrc', dest: '{{homedir}}/.vimrc' }
    - { src: 'wgetrc', dest: '{{homedir}}/.wgetrc' }
    - { src: 'terminator.config', dest: '{{homedir}}/.config/terminator/config' }