- name: Test docker is installed
  stat:
    path: /usr/bin/docker
  register: docker_stat_result

- name: Install docker
  local_action:
    module: shell curl -fsSL https://get.docker.com | bash
  notify: 
  - Restart Docker
  when: not docker_stat_result.stat.exists

- name: Add user to group
  local_action:
    module: shell usermod -aG docker {{ user }}
  when: not docker_stat_result.stat.exists