- name: Include Vars
  include_vars: "vars-{{ansible_distribution}}.yml"

- name: VSCode PGP Sign
  local_action:
    module: apt_key
    state: present
    url: "{{ ms-gpg-key }}"

- name: Create Teams Repo
  local_action:
    module: shell echo -e 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/ms-teams stable main" > /etc/apt/sources.list.d/teams.list'

- name: Install Microsoft Teams.
  local_action:
    module: apt
    deb: teams
    update_cache: yes
    install_recommends: yes
    state: present