- name: Include Vars
  include_vars: "vars-{{ansible_distribution}}.yml"

- name: Test Google Chrome is installed
  stat:
    path: /usr/bin/teams
  register: teams_stat_result

- name: Teams PGP Sign
  local_action:
    module: apt_key
    state: present
    url: "{{ msGpgKey }}"
  when: not teams_stat_result.stat.exists

- name: Create Teams Repo
  local_action:
    module: shell echo "deb [arch=amd64] https://packages.microsoft.com/repos/ms-teams stable main" > /etc/apt/sources.list.d/teams.list
  when: not teams_stat_result.stat.exists

- name: Install Microsoft Teams
  local_action:
    module: apt
    name: teams
    update_cache: yes
    install_recommends: yes
    state: present
  when: not teams_stat_result.stat.exists
