- name: Upgrade all packages
  local_action:
    module: dnf
    name: "*"
    state: latest

- name: Install RPM Fusion Repo
  local_action:
    module: dnf
    name: "{{ item }}"
    disable_gpg_check: yes
    state: present
  with_items:
    - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
    - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm

- name: Install DNF common packages
  local_action:
    module: dnf
    name: "{{ packages }}"
    state: present