- name: Include Vars
  include_vars: "vars-{{ansible_distribution}}.yml"

- name: Test MS VSCode is installed
  stat:
    path: /usr/bin/code
  register: vscode_stat_result

- name: VSCode PGP Sign
  local_action:
    module: apt_key
    state: present
    url: "{{ msGpgKey }}"
  when: not vscode_stat_result.stat.exists

- name: Create VSCode Repo
  local_action:
    module: shell echo "deb [arch=amd64] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list
  when: not vscode_stat_result.stat.exists

- name: Install Microsoft VSCode
  local_action:
    module: apt
    name: code
    update_cache: yes
    install_recommends: yes
    state: present
  when: not vscode_stat_result.stat.exists