---
# tasks file for install-packages
# - include: install-{{ansible_distribution}}-common-packages.yml

- name: Include Plugins
  include: "{{ installPackagesTaskDir }}/install-{{ item }}.yml"
  with_items: "{{ installPackagesPlugins }}
  