---
# tasks file for install-packages
- include: install-{{ansible_distribution}}-common-packages.yml
- include: install-docker.yml
- include: install-{{ansible_distribution}}-vscode.yml
- include: install-nxc-client.yml
- include: install-aws-cli.yml
- include: install-{{ansible_distribution}}-chrome.yml
- include: install-{{ansible_distribution}}-zoom.yml
- include: install-{{ansible_distribution}}-teams.yml