---
# tasks file for install-packages
- include: install-common-packages.yml
- include: install-docker.yml
- include: install-vscode.yml
- include: install-nxc-client.yml
- include: install-aws-cli.yml
- include: install-chrome.yml
- include: install-zoom.yml
- include: install-teams.yml